matrix:
  include:
    - env: ver=0.12.6
    - env: ver=0.12.5
    - env: ver=0.12.4
    - env: ver=0.12.3
    - env: ver=0.12.2
    - env: ver=0.12.1
    - env: ver=0.12.0
    - env: ver=0.11.14
    - env: ver=0.11.13
    - env: ver=0.11.12

os: 
  - linux-ppc64le
sudo: required
services:
  - docker
language: go
go:
- "1.12.1"

# add TF_CONSUL_TEST=1 to run consul tests
# they were causing timouts in travis
# add TF_ETCDV3_TEST=1 to run etcdv3 tests
# if added, TF_ETCDV3_ENDPOINTS must be set to a comma-separated list of (insecure) etcd endpoints against which to test
env:
  - CONSUL_VERSION=0.7.5 GOMAXPROCS=4 GO111MODULE=on

# Fetch consul for the backend and provider tests
before_install:
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir -p ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"

install:
  - sudo apt update
  - sudo apt-get install lftp
  - python3 ftp_version.py

script:
- bash build.sh
